
-- [연습 문제]
-- 회원가입용 테이블 생성(USER_TEST)
-- 컬럼명 : USER_NO(회원번호) - 기본키(PK_USER_TEST), 
--         USER_ID(회원아이디) - 중복금지(UK_USER_ID),
--         USER_PWD(회원비밀번호) - NULL값 허용안함(NN_USER_PWD),
--         PNO(주민등록번호) - 중복금지(UK_PNO), NULL 허용안함(NN_PNO),
--         GENDER(성별) - '남' 혹은 '여'로 입력(CK_GENDER),
--         PHONE(연락처),
--         ADDRESS(주소),
--         STATUS(탈퇴여부) - NOT NULL(NN_STATUS), 'Y' 혹은 'N'으로 입력(CK_STATUS)
-- 각 컬럼의 제약조건에 이름 부여할 것
-- 각 컬럼에 주석 달기
-- 5명 이상 INSERT할 것 


CREATE TABLE USER_TEST(
	USER_NO NUMBER CONSTRAINT PK_USER_TEST PRIMARY KEY,
	USER_ID VARCHAR2(20) CONSTRAINT UK_USER_ID UNIQUE,
	USER_PWD VARCHAR2(30) CONSTRAINT NN_USER_PWD  NOT NULL,
	PNO CHAR(14)CONSTRAINT NN_PNO NOT NULL,
	GENDER VARCHAR2 (10) CONSTRAINT CK_GENDER CHECK(GENDER IN('남','여')),
	PHONE VARCHAR2(30),
	ADDRESS VARCHAR2(100),
	STATUS VARCHAR2(10)DEFAULT 'N' CONSTRAINT NN_STATUS NOT NULL ,
	CONSTRAINT CK_STATUS CHECK(STATUS IN('Y','N')),
	CONSTRAINT UK_PNO UNIQUE(PNO)
	
	
);

COMMENT ON COLUMN  USER_TEST.USER_NO IS '회원번호';
COMMENT ON COLUMN  USER_TEST.USER_ID IS '회원아이디';
COMMENT ON COLUMN  USER_TEST.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN  USER_TEST.PNO IS '주민등록번호';
COMMENT ON COLUMN  USER_TEST.GENDER IS '성별';
COMMENT ON COLUMN  USER_TEST.PHONE IS '연락처';
COMMENT ON COLUMN  USER_TEST.ADDRESS IS '주소';
COMMENT ON COLUMN  USER_TEST.STATUS IS '탈퇴여부';


INSERT INTO USER_TEST
VALUES(1, 'MINNI','PASS01', '960118-2122345', '여', '010-2345-7891', '서울시 강남구','N');

INSERT INTO USER_TEST
VALUES(2, 'u_JA_nG','PASS02', '000315-2234567', '여', '010-5678-9999', '서울시 강동구','N');

INSERT INTO USER_TEST
VALUES(3, 'suckHY0N','PASS03', '990527-1122345', '남', '010-4567-1234','수원시 권선구', 'N');

INSERT INTO USER_TEST
VALUES(4, 'DDA501','PASS04', '930917-2127894', '여', '010-8888-1111','대전광시', 'N');

INSERT INTO USER_TEST
VALUES(5, 'MInchan','PASS05', '971113-1122344', '남', '010-7775-0054','부산광역시', 'N');


SELECT  * FROM USER_TEST;

SELECT * FROM USER_COL_COMMENTS0
WHERE TABLE_NAME = 'USER_TEST';

