--1.
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT 
ORDER BY 1;
 
--2. 
SELECT STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

--3.
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE) LIKE '%1'
AND STUDENT_ADDRESS LIKE '경기도%'
OR STUDENT_ADDRESS LIKE '강원도%';


--4 
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO LIKE '005'
ORDER BY 2 ;

--5 
SELECT STUDENT_NO, ROUND(POINT,2) 
FROM TB_GRADE
WHERE TERM_NO LIKE '200402%'
AND CLASS_NO IN ('C3118100')
ORDER BY 2 DESC ;

--6. 
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT;

--7 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
NATURAL JOIN TB_DEPARTMENT;

--8(다시하기)
SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS_PROFESSOR 
NATURAL JOIN TB_CLASSNATURAL JOIN TB_PROFESSOR
GROUP BY CLASS_NAME, PROFESSOR_NAME;

--9(다시하기)
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR CP
LEFT NATURAL JOIN TB_CLASS C
LEFT NATURAL JOIN TB_PROFESSOR P
LEFT JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO =D.DEPARTMENT_NO)
WHERE CATEGORY IN('인문사회');

--10 
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) AS "전체 평점" 
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
NATURAL JOIN TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME ;


--11. 
SELECT DEPARTMENT_NAME "학과이름", STUDENT_NAME "학생이름", PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO IN ('A313047');



--12.
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT
NATURAL JOIN TB_CLASS 
NATURAL JOIN TB_GRADE
WHERE TERM_NO LIKE '2007%'
AND CLASS_NAME ='인간관계론';

--13. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

--14
SELECT STUDENT_NAME "학생이름", NVL(PROFESSOR_NAME,'지도교수 미지정') AS "지도교수"
FROM TB_STUDENT
LEFT NATURAL JOIN TB_DEPARTMENT
LEFT JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME  = '서반아어학과';

--15.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;


--16. 
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8) "AVG(POINT)"
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;


